const healthCodes = {
  NOT_STARTED: 0,
  SUCCESS: 200,
  ACCEPTED: 202,
  IN_PROGRESS: 1,
  DEPLOYING: 3,
  STAGING: 4,
  BUILD_STARTING: 9,
  BUILD_CLONING: 10,
  BUILDING: 11,
  BUILD_UPLOADING: 12,
  VERIFYING: 13,
  CONTAINER_STARTING: 21,
  BAD_REQUEST: 400,
  FAILED: 500,
};

export default healthCodes;
